#!/bin/sh

set -e

lb config noauto -a amd64 -d bookworm \
	--firmware-binary false \
	--firmware-chroot false \
	--apt-recommends false \
	--archive-area main,non-free-firmware \
	--bootappend-live "boot=live components intel_iommu=on iomem=relaxed nomodeset persistence"
	"${@}"
